image: ubuntu:22.04

variables:
  FLUTTER_VERSION: "3.29.0" 

before_script:
  - apt-get update && apt-get install -y curl git unzip xz-utils zip libglu1-mesa
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1 /flutter
  - export PATH="/flutter/bin:$PATH"
  - flutter doctor -v
  - flutter --version

pages:
  stage: deploy
  script:
    - cd example
    - flutter pub get
    - flutter build web --release --wasm
    - cd ..
    - rm -rf public
    - mv example/build/web public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

cache:
  paths:
    - example/.pub-cache/
    - example/build/ 