image: ubuntu:22.04

before_script:
  - apt-get update && apt-get install -y curl git unzip xz-utils zip libglu1-mesa
  - git clone https://github.com/flutter/flutter.git /flutter
  - export PATH="/flutter/bin:$PATH"
  - flutter channel stable && flutter upgrade && flutter doctor

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - flutter pub get
    - flutter test
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build:
  stage: build
  script:
    - cd example
    - flutter pub get
    - flutter build web --release --wasm
    - cd ..
  artifacts:
    paths:
      - example/build/web/
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv example/build/web public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

cache:
  paths:
    - example/.pub-cache/
    - example/build/
    - .pub-cache/
