name: new_loading_indicator
description: Fork of the loading_indicator package.
version: 0.0.1
repository: https://github.com/sunderee/new-loading-indicator

environment:
  sdk: ">=3.7.0"
  flutter: ">=3.29.0"

topics:
  - loading-indicator

dependencies:
  async: ^2.12.0
  collection: ^1.19.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
