name: new_loading_indicator
description: A fork of the loading_indicator package, providing a rich collection of loading animations for Flutter applications.
version: 1.1.0
repository: https://github.com/sunderee/new-loading-indicator

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.6"

topics:
  - loading-indicator

dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
