name: new_loading_indicator
description: A fork of the loading_indicator package, providing a rich collection of loading animations for Flutter applications.
version: 1.0.0
repository: https://gitlab.com/dart-and-flutter-packages/new_loading_indicator#

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

topics:
  - loading-indicator

dependencies:
  async: ^2.12.0
  collection: ^1.19.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
